/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ajuda.java
 *
 * Created on 24/09/2010, 22:10:01
 */

package compilador.gui;

/**
 *
 * @author Gabriel
 */
public class Ajuda extends javax.swing.JFrame {

    /** Creates new form Ajuda */
    public Ajuda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Estrutura Léxica da Linguagem");

        jTextPane1.setContentType("text/html");
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jTextPane1.setText("<html><b style=color:green>Palavras reservadas:</b> <b>variaveis, metodos, constantes, classe, tipo, retorno, vazio, principal, se, entao, senao, enquanto, para, leia, escreva, inteiro, real, logico, caractere, cadeia, verdadeiro, falso, herda_de</b>\n<br><br>\n<b style=color:green>Identificadores:</b> <b>Letra ( Letra | Dígito | _ )*</b>\n<br><br>\n<b style=color:green>Número:</b> <b>( - )? Dígito+ ( . Dígito+ )?</b>\n<br><br>\n<b style=color:green>Letra:</b> <b>( a..z | A..Z )*</b>\n<br><br>\n<b style=color:green>Dígito:</b><b> 0..9</b>\n<br><br>\n<b style=color:green>Simbolo:</b> <b>ASCII de 32 a 126 (exceto 34)</b>\n<br><br>\n<b style=color:green>Cadeia constante:</b> <b>\"( Letra | Dígito | Simbolo )*\"</b>\n<br><br>\n<b style=color:green>Operadores:</b> <b>+  -  *  / == != > >= < <= && || = ++ -- .</b>\n<br><br>\n<b style=color:green>Delimitadores:</b> <b>; ( ) { } [ ] </b>\n<br><br>\n<b style=color:green>Comentários:</b>  <b> /*isto é um comentário de bloco */</b><br>\n\t                 <b>// isto é um comentário de linha</b></html>\n\n");
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Padrões de formação da linguagem:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ajuda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
